  
sudo: required
services:
  - docker

script:
  - docker-compose build
  - docker-compose up


deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "myJournal"
  env: "myJournal-env"
  bucket_name: "deployment-sandbox-nodejs"
  bucket_path: "myjournal"
  on:
    branch: master

  access_key_id:
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
